# Netlify configuration file

# Since this is a static site, no build command is needed
[build]
  publish = "."

# Configure headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://api.qrserver.com data:; connect-src 'self' https://eodhd.com https://generativelanguage.googleapis.com;"

# Redirect 404 errors to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
